[phases.setup]
nixPkgs = ['php81', 'php81Packages.composer']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = [
  'php artisan config:clear',
  'php artisan route:clear',
  'php artisan view:clear',
  'php artisan config:cache',
  'php artisan route:cache'
]

[start]
cmd = 'php -S 0.0.0.0:$PORT -t public'